archivesBaseName = "${mod_name.replace(" ", "")}-Fabric-${minecraft_version}"

dependencies {
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation project(":Common")
}

//accessWidenerPath = file("src/main/resources/morecreative.accesswidener")

unimined.minecraft {
    fabric {
        loader fabric_loader
        accessWidener(file("src/main/resources/morecreative.accesswidener"))
    }
}

preRunClient.enabled = false

processResources {
    from project(":Common").sourceSets.main.resources
    def buildProps = project.properties.clone()

    filesMatching(['fabric.mod.json']) {
        expand buildProps
    }
}

compileTestJava.enabled = false

tasks.withType(JavaCompile).configureEach {
    source(project(":Common").sourceSets.main.allSource)
}
