archivesBaseName = "${mod_name.replace(" ", "")}-Fabric-${minecraft_version}"

dependencies {
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation project(":Common")
}

unimined.minecraft {
    fabric {
        loader fabric_loader
        accessWidener(file("src/main/resources/morecreative.accesswidener"))
    }
}

preRunClient.enabled = false

processResources {
    from project(":Common").sourceSets.main.resources
    def buildProps = project.properties.clone()

    filesMatching(['fabric.mod.json']) {
        expand buildProps
    }
}

compileTestJava.enabled = false

tasks.withType(JavaCompile).configureEach {
    source(project(":Common").sourceSets.main.allSource)
}

publisher {
    apiKeys {
        modrinth(System.getenv("MODRINTH_TOKEN"))
        curseforge(System.getenv("CURSE_TOKEN"))
        nightbloom(System.getenv("PLATFORM_KEY"))
    }

    setCurseID(curse_id)
    setModrinthID(modrinth_id)
    setNightbloomID("morecreativetabs")
    setVersionType("release")
    setChangelog("https://raw.githubusercontent.com/hypherionmc/changelogs/main/mct/changelog-fabric.md")
    setProjectVersion("${minecraft_version}-${project.version}")
    setDisplayName("[FABRIC/QUILT 1.20/1] CraterLib - ${project.version}")
    setGameVersions("1.20", "1.20.1")
    setLoaders("fabric", "quilt")
    setArtifact(remapJar)
    setCurseEnvironment("client")

    modrinthDepends {
        required("fabric-api")
    }

    curseDepends {
        required("fabric-api")
    }
}