plugins {
    id 'java'
    id "xyz.wagyourtail.unimined" version "1.3.15" apply false
}

version = mod_version + "+" + minecraft_version
group = maven_group

subprojects {
    apply plugin: "xyz.wagyourtail.unimined"
    apply plugin: 'java'

    java.toolchain.languageVersion = JavaLanguageVersion.of(17)

    version = rootProject.version
    group = rootProject.group

    base {
        archivesName.set("${rootProject.archives_base_name}-${project.name}")
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        compileOnly("org.projectlombok:lombok:${lombok}")
        annotationProcessor("org.projectlombok:lombok:${lombok}")
    }

    unimined.minecraft(sourceSets.main, true) {
        version minecraft_version

        mappings {
            intermediary()
            mojmap()
            parchment("1.20.1", "2023.09.03")
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = 17
    }

    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }
}
