pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url = uri("https://maven.wagyourtail.xyz/releases")
        }
        maven {
            url = uri("https://maven.wagyourtail.xyz/snapshots")
        }
    }
}

rootProject.name = 'MoreCreativeTabs'
include("common", "fabric", "neoforge")
